// <auto-generated />
using System;
using MiamBurger_API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiamBurger_API.Migrations
{
    [DbContext(typeof(MiamBurgerContext))]
    partial class MiamBurgerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiamBurger.Model.Burger", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Number");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Burgers");
                });

            modelBuilder.Entity("MiamBurger.Model.Order", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"));

                    b.Property<DateTime>("DTOrder")
                        .HasColumnType("datetime2");

                    b.Property<int>("NbUser")
                        .HasColumnType("int");

                    b.HasKey("Number");

                    b.HasIndex("NbUser");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MiamBurger.Model.OrderLine", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"));

                    b.Property<int>("NbBurger")
                        .HasColumnType("int");

                    b.Property<int>("NbOrder")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Number");

                    b.HasIndex("NbBurger");

                    b.HasIndex("NbOrder");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("MiamBurger_API.Model.User", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"));

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Number");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MiamBurger.Model.Order", b =>
                {
                    b.HasOne("MiamBurger_API.Model.User", "user")
                        .WithMany()
                        .HasForeignKey("NbUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("MiamBurger.Model.OrderLine", b =>
                {
                    b.HasOne("MiamBurger.Model.Burger", "burger")
                        .WithMany()
                        .HasForeignKey("NbBurger")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiamBurger.Model.Order", "order")
                        .WithMany()
                        .HasForeignKey("NbOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("burger");

                    b.Navigation("order");
                });
#pragma warning restore 612, 618
        }
    }
}
